version: '3.8'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    depends_on:
      - es
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200